name: algorithm
services:
  algorithm-class:
    build:
      context: .
      args:
        USERNAME: user
    image: tedwang2/algorithm-class:1.1
    container_name: IClab
    stdin_open: true
    tty: true
    privileged: true
    network_mode: host
    working_dir: /home/user/tone_mapping
    environment:
      - DISPLAY=host.docker.internal:0.0
      - XAUTHORITY=/root/.Xauthority
    volumes:
      # Mount X11 server
      - /d/.Xauthority:/root/.Xauthority
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      # Direct Rendering Infrastructure
      - /dev:/dev
      - ../tone_mapping:/home/user/tone_mapping
    
    stop_grace_period: 1s
    command: /bin/bash